# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6f62b011e068c635e2adceffc49b11c22be0f4309bf357e089c0325bccb2720a9cb30193dbb1a1b2b73e01bc467dcd93fca4fa480892ad5855d57a568ac514de

test:
  secret_key_base: 29ffabe2b3d9193543f50c6fc73e166a15e6f8d93c38935f7e4464c278d0a50baea92d352cb67a484056f89146112d3ed428f5d9a5f442a9d6b2c563d2758d8b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
